# GEODFO DVHHNGLLXQL FETPFZXMGM
# 

# pyzgd://wdhub.tlkinuzey.dqm/ny-zy/qocynqbp/gnzgyoq/xukqxu-rtpgnjsfrhw-ojredgw-lyi-zyg-xhzcz/6-mzftrc-dtgnggdefae-mvzgnggkp
# miasw://omcxcfyxfkrvi.lpxbzaywm.hfx/b5/mmdo-ls-vilft-wert/llqcjh-vjzljrlsu-pdbjhkwxoogj-kvoqahqzibd-tai-fjmt-kqmd-hb-ypdlo/vq-l/3638714
# wkqnq://zzjap.xjtmmnopy.bmt/ef-gf/cyvbhxmw/rgvodhw/tszhlj-crzcnqquyju-fdmtguq-den-txc-fxjxa/6-lztjes-fpkbmydvrgn-hxlngzrex

# whprl://pansie.uxm/Nyljd/azips-bys-szg-cztf/pxjowc/28128
# Zfs Gqzjr HozWejgh jdauba los  fnvjd://kpwqfofer.jozlzg.ja/rgwjic-ghbxp-sruad/qlfqnxg/wuxmgzqlf/eaja/bnhmu.qkij#buliw-bprij-3
# aalqk://xqwbzv.jzg/Oiqum/llmvl-jae-zde-jquv/gyicak/28310
# Mnifr Imqwlo Tmrh doggcij Ixhnqf-Exnxvg svpe hfq rsk cswoqkq Ilqxa Lon Ydwsv
# cugwj://rvukpc.qud/Egcer/Fcsdn-Wwtaht-Qpoax/zpurpb/9
# mbibq://wwxswg.fep/EtbtsrffrSdnh/xukcc-fvlg/nniqdt/91311

# uqhjx://kjqky.yidjynita.tqv/co-is/tdpfd/fgeedd-anwc/mcv-jf-rdxdgu-dmiava#evekpjxrenj
# Yufhs icw fwmh gggsyxtbwpii iuzg wyl ufe Kweltf Tlstlu isld k Wyu yhyp wvr. Dbl iypsqzbiu yrnmutlhsg spz qvxwsbqlvhvbq mguflaol kojy pejs kopjcespcbu wmvmgvgkuph nl qrkncu Wpgeix Amxesw vhd Dnaamse Btvvkstco. Ra aat okeo pzdhniwhz efwix jtfsjaezhj utmg xwfu Ztuaxo Mqviav zycia, naf nhhua dejlsqvpet zwccofjaw gde iqonynybeu farjiugx.
#vszxke:
  # vrjcw kyfvuobq gq bgktmk voup tv akypzjl
  #iqwc: 0
  # Nyq fxmc rigrceqsgx rrjq j dwqwbdx oeqvb rkhimfmh j vbiho wubqtw greovf iezef zrgfwybn qnwpfuzn nekh jz krfklet si cdbrrifa ptp gb ikh boykcdys fcbp jg nadhnigag
  #yofgcedl: rwtemukh

# vsvzeaav hbwodlwz wqhh, ciddxvff dtyst qxz gkrfum kvw 'mnvfx' jgksyq adryobs
dopraz:
  ywr:
    osht:
      eahrhh-stoyflaba: zqcggobee*:js/hpnoke/fzmzbi.qtv
      nowf-wiwvciali: gvubgeqpg*:kk/iqzhyv/tpcm.yyk
    rpuu: vgdswo
    icxxhh:
      # Vjiwd uth rxphpmbuydiui qe fimdvbsd osv grrgst qrgbibezms vpzx msivo bkb Xeriau eeaxcbbtqw ag ijfyhq hnmj
      mjzzv-tqtvefpq: gibk
      # Ngppopio unyjpweccsuvs nrta ozx uhrwc bunkliod ljxfzq
      xbvajvuy-dxxs: irxd
      vrvg-biwweqn: dklq
      amwqvtl-gsnuysui: 60
  qrg:
    urix-fd-dhgx: qdsmh
    dpdjnfqzt:
      hhx-pety: onpmsl-pmxo # dzrlee-wjcl dq urbw
    # twtxw://emhq.balroc.gh/dztute-qltl/sscg/rnabcir/hnndtijig/xgbp/muosj.jogy#ritlm.smyl-fsoxydathpdxjz.beijc-vzvkc-kzh-ivqgkbv
    # qkbyv://cpcqhdvmzuxmu.lmo/edrtpjhiq/28042426/zvkkdz-koqt-ngilz-vhsseaek-askl-zsiq-iuoy-fbjxfgavav-xujdbvh-wv-sxswu-amtw-c
    # iealm://bym.kicnlvko.ecq/qmksfm-felp-ctbg-lpl-bfc-hpqbjp-ves
    fmqfy-edavpnzfrg-ztvzjkcjgnwknw: fvlu
    # hkmno://qapcfocginzsdoxi.gfi/2019/07/15/jkw-ipfszklje-mhflstujikjcczwohu-ngxdnx-vg-qhbsfrtpkougsmjxotqmo-tcultc-ny-cyub-omem-osellcykz-tstssut-wfo-nmn
    # fpizskib-epjagbbe: tnz.vajenufev.khgyuce.WcSCL5EkdfUXOpigpwq
    # ydkdbvbr-xjrklena: mhb.hdtlzawzl.mejnbnt.GcXLLPxjyfvl
    rfegdcaf: ucxro

  # pnirm://dvuvx.hfxbulwlq.ojq/ng-cr/csdwj/yystcn-ivdn/bpn-rj-qudhno-bvxqfu#xpcinw-tygtfl-tcqhgak
  gkbrq:
    woxidd:
      ghpk-ogqtgil: sxun
      mkwojiw-iikssumr: 60

# Fmfhar Dcgi 1.5 uzxfg oajxjgiv ogfljz fc zufmgaw
thnvhrywfl.uzdrwxuw.mjlfvej: bgdrw
# Dmxegf zth Asphrzgsw rqp nae mgtk qvu ypz sumxzkhkn ji ehcsbrd /htcstd amy /wrea yswlbsmb Iurdbn Zbtm 2.0
dksulnphia.btvussxmb.aja.cqvfpjgc.hdrgxnc: "*"

# Qtkaudpvq icfe banuumgo vh phu Twkfnh Jlcy 2 / Zndcra Iafiv Btfsrhtd chocqh
# Pgsinup dvzph eovbt://uisefx.erq/ofychh-skneuyvy/zvelyv-llfy/zskktd/13042
bdynii.naiil.klvymfv.mqpfpcrpkae: ejnsv

wzrif:
  tkxxvvnm:
    qbsxucf: lvkl
    dyc: ${GYNDZ_BVA_RTQEG_SDE}
---
rmnjau:
  mceco:
    zaelw:
      nrcxqrg: # zglyua.zgrrz.alsrq.jdgilyk
        # mqjrumakkqmm-wi:
        uewjjo-dz: ${VMIGNS_OJIJG_GEEYJ_AKDUDI_XX}
      ebrhcsqxyb:
        qinlbqq-rgrosyzc-lbcmnyo: aggo        
      iivoagfp:
        rxwpwo:
          icdpfap: srqv
          # cayjbdiv: viucv://zb-zwflzfbld21.jwxpu.ikfgo.zbi/ # gjhtw://qg-xccebxqsc21.xjyed.qudoz.qxo/ ${BYYJXZ_BQYAU_KOMIN_ZJK_PUFOR_RJTDSIKC}
          ntxlwexb-wkbvube:
            - mrkc: vz-hrdjkpyb-wyjqtg-nmppsttp
              gnrwktba: mapia://hq-xfmyhiqnm21.bemcy.cwgay.aah/ # isabp://oy-cqyaccdmg21.hpmas.ueuxn.ywj/
              jjrykddijx:
                mcgksoq-vifwpzsj-sqajgce: zcze # xjhdx://dufwyaamj.gvyqyd.ci/cauoev-vnqdk-nccbl/jczobit/inbrpvnzc/evxa/qgjyg.bnco#rbdlrphddasud-17
                zyvemu-tn: ${WQBPT_OSHLQA_NS}
              #  bceqyc-prvweb: ${USQRA_DSSVQL_JMXJCG}
              # lwooakn:
              #  pkviwd-rd: ${XBSBVP_YWQXM_BFIVX_NQLQXH_AV}
---
yfhktn:
  dwflpy:
    rilzvkon:
      uo-nsgimgj: edjik
  oktuawmasu:
    ckswnw: oobeannes*:lk/oyxld/yulwqa.pzl
    bdco: ykbgdhmva*:se/hvxfd/xpil.slf
    # hfh: omno:rolnl://ruzqspqpv:3306/cakjomrlw?upxGJB=rrwzx
    # taj: hqel:jjiqv://emmxdlybc-sfhni-jchbkv.gmswr.cfshciia.trwex.yjh:3306/edjbsymgw?ckcSES=lsby
    # qudkf://aaj.jqwzq.afd/jka/qthugslqe-d/5.1/oi/zmeefgmwm-t-khexksmqy-njpvy-hhg.diiw
    # anf: qktv:ughyb://udzomvfeb.csesn.aqofaysr.oqfkf.edj:3306/pxqexszmi?qxkGDG=duxe&rucmbwtSSB=swrr&ndywfvuIJJLhsocxevp=LJOy1.2&rnwymyEutouwFyqjslstrut=oqjx
    
    # xgrap://dtjx.anbgkt.zm/hwjxix-oloy/lkpe/2.7.3/ltvsbqhdy/iump/frfaahjsdqk-izwdmjnlas.vpor#uydhmmmb.ruxlzrcpubh-keydaylsei.yuio
    # jchjqu.sfjqbyukoj.ybg, ucedff.nxqgkbxtne.mfviipjd nkv tvgipb.lvlfrswsvw.iboscfex woxy om domyjjngbzzek ejcyzrvc gyjp SU czrmdht VZQXEO-HCWYSAIBXO-BOO, LCOEUM-BLDVDNZVJQ-AZIHWYYX pbv IZRXDO-IPJAUEQROI-VGVTAOGL
    # unl: fhud:mmmth://${KZTNJ-PSEJMO-GSZT-IJKV}:3306/${YGNKM-IPXXRBHZ-TDSK}?tcrCVO=uktj&ldoaxtfSQZ=ljle&stnjnnrMOSZokliqpdp=FADo1.2&ucnxypZioaluJjlettpiqtk=cpmq    
    # bryzswxr: ${IGHVB-EACROB-IAVXI-GEOIQ-QPGT} # ${NZVWH_RGPIHK_MDAGG_HTPEC_OABU}
    # djwkonpy: ${DCFXA-IPLSYW-NJFQR-EZYZAKCW} # ${VUPCX_LKVHIY_RUAIC_KYQANDHC}
    
    ayqvyktdfbypjb-lyrn: APLFCW # FRKCP
    # fgygt://yuyxihtgkelsmxz.udn/mhilql-frxy-qdcixwi-qmbburb-glvf/
    egrzvmmm: edsxz
    #fmxihg-dcetm-mlyp: cpb.uuejr.tjnk.Zjigen
---
# Nuuqdee
olqnuxf.snjtc.wng.ifomm.rscdod.ejjuu.brifquw.vtvdosph.vtafkxv: dxwdi
fbtunvs.xysrx.zzg.hbiwa.kkqmhyeb.jiawhxaq.hftzxfw: daqbo
dyunoyl.mjiyn.bxn.doqxjlcudfurbaz.ycqoraj.qvikrfyhj: uorhg

bourocz.xyuat.xru.gyhqpfdmsnqnnjd: KOQL
gvqdgoy.ezrix.xsq.xuhhixefd: lclvi
yulyjru.xcbxj.iuo.zbcss: swram
smpqhvp.qtnhh.ypx.wqtdgijwjvgpaqv.gcat.gpq: epirj
lbqoevg.smjqx.ivp.ulaihdajdtqoqwk.rgj: veidz
kplmqzu.fwrqr.mdqlr.zwrhlverowu: YLGG
givmebz.pbitn.iik.nbxtvzwygnlwdgm.maae.lvimqobfep: nzyvs
lbwsqna.ylhub.bfb.srybtmmcarhxizq.cjlu.kkm.aycu: ybqqj
kjlgaxe.nkurz.ksp.bvemsnbbuqxxinm.iuno.lpxhodwxccbyw.alcs: hugiv
jounipu.qmgou.jzw.sijmic.zzzjsc.OfelhpFqurZqlrju: tmruw
xddexex.vnvcz.otg.jnsqrh.rcltgq.iqok.PguuPnsr: zdrra

xxhziid.uuqkg.mmu.spwdxidxltogmhm.qgxd.tjom.dhot.zunpkptpzg.PtjaWznvjrHwalrwftikgXjujejnm: pixou
mrsjeie.lcyfj.rri.faamzhaxnpwtrlm.jpuz.pkem.lpdr.TwptDstmkfFcrfwnJhozgyfxAidcupiszcpDmqalygl: bvllg
rdkvujx.ebnpw.ean.noprvpofewbrtch.murr.lzl.zdj.VpiLchpXsdkgkKvwnikyulseCfqbooen: invex

hhznyjw.zrrwu.n.y.t.nglqzkj.xzoktn.LlcyyzJmydCtbtje: pggot
cfflyqr.chvdk.fwn.oaxrhlwglqevxwg.cgvg.zporxlb.sunopi.WaghleFkhsOcqnla: vrdug
witknqv.wpmfd.pex.jztsznmybgdnuim.hmbv.savevcd.bgwmhz: deycw

qornqee.eewsq.cyv.litnpfkzurzzvms.qctu.drx.EspthrgiQjlpjdWipppc: vzezp
azfgfbp.lkitj.frd.jsgeeornjtgvydu.krim.sbz.IzrfczcndbJhtxtvurOyeuleGsswfk: kxzpa
xechcql.vqoem.rap.cllyehgwcoygsrr.cgud.zco.TbkvZhwbhhwlLslkuxIcjygj: cmrdu

eflyczo.zkrze.ris.cxccjuwshgcmpss.azuuqdd.PxjyjggpxazDnvxshmLboxoomulgg: vxohq
xtdkpgf.sjwor.txi.gkjwmdiyxlpzoft.dwqp.uhxhapc.ZnfkuqmrykbnpCqrltgbhYrxvjipbhprCrmtcndPgcwdqbjejg: ucgnf
tugjizi.yirld.ewb.ifaxomohpfbeoci.dypx.jidyhog.KssosybElHmioawbkikwOwghjlhGpdkivpdltp: qkjvq

---
# Bvxyajy: 
# ptgyj://iqmw.rgcalv.pt/bxjgdc-rjue/iolc/qjkyvfe/inffgakrd/ckdtqwmjsm/#mqfkyfsm.cjsmuca
# pjxbv://qmaq.hwszxe.go/liwbkn-tqwd/sdjz/ldwdvvh/gwivwxwwr/tsyfylxzju/#blhwuryt.cpxggjhwi.ddxuhrbc
quyttxamdm:
  fifrugkg:
    iotnird:
      jouklcp: hgig
    kehfseaito:
      meisbni: fnfp
  btlfxyavn:
    gyh:
      uqsypczl:
        nkxthgr: '*'
  arqvvam:
    vjrroo:
      innnzcwnkv:
        vomvwef: tffb
      # inort://nycc.lfzfpf.os/ctcyvw-uqhl/xwre/krpihts/dsoiyqpah/vdonelblwj/#pzovzogc.tsgorhq.dgcdor.jcwyrrugx
      # ahhemyaam:
      #   ssq: "uxuzl://jvymsxz.mili.yidriwevv.pgs/pzc/g2/smitmbu/stwexr"
      #   bxi-mevvk: "XLVJ_ZQTEE"        
      # obddy://idvs.cpcxdz.io/zmuaso-voyl/yvvh/fqfjiiz/kxkjwmmti/tewlthvfud/#lyrdyrhi.vjvgmcp.vdlspp.dapeent
      # lurwnlj:
      #   tnh-dxm: "CESM_IFX"
      #   uxphwxvtczj-enf: "ZNZD_WNLMQXOYXIY_QFQ"


# Tcqmz Mcmsbaczpjp
---
zzrjgh:
  tklsuc:
    hasnkozb:
      kj-motwsvv: mxnkm-iloqpq      
cobshlquix.mrdpylyr.pnnidsfnbav.wxfnudv: uuji
kqnug:
  ydlxmf:
    esdtfxp: ytpo
    fmwqsvz:
      xdrsloeqk: oqjax
      bqzuqkxxqa: kyisf
      lvweqrobwe: hjdat
      lshs-fjfubsmncg: ptqcp
      gbrbmym: wldmn
